package com.example.weather.WebServices

data class WeatherDaily(val summary: String,
                        val icon: String,
                        val data: List<WeatherDailyData>)

data class WeatherDailyData(val time: Long,
                            val summary: String,
                            val icon: String,
                            val sunriseTime: Long,
                            val sunsetTime: Long,
                            val moonPhase: Double,
                            val precipIntensity: Double,
                            val precipIntensityMax: Double,
                            val precipIntensityMaxTime: Long,
                            val precipProbability: Double,
                            val precipType: String,
                            val nearestStormDistance: Double,
                            val nearestStormBearing: Double,
                            val temperatureHigh: Double,
                            val temperatureHighTime: Long,
                            val temperatureLow: Double,
                            val temperatureLowTime: Long,
                            val apparentTemperatureHigh: Double,
                            val apparentTemperatureHighTime: Long,
                            val apparentTemperatureLow: Double,
                            val apparentTemperatureLowTime: Long,
                            val dewPoint: Double,
                            val humidity: Double,
                            val pressure: Double,
                            val windSpeed: Double,
                            val windGust: Double,
                            val windGustTime: Double,
                            val windBearing: Double,
                            val cloudCover: Double,
                            val uvIndex: Long,
                            val uvIndexTime: Long,
                            val visibility: Double,
                            val ozone: Double,
                            val temperatureMin: Double,
                            val temperatureMinTime: Long,
                            val temperatureMax: Double,
                            val temperatureMaxTime: Long,
                            val apparentTemperatureMin: Double,
                            val apparentTemperatureMinTime: Long,
                            val apparentTemperatureMax: Double,
                            val apparentTemperatureMaxTime: Long)
